### ISSUE TITLE
Proxy UI enhancements

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/skale-proxy#11]
Things to add to proxy ui:

- [x]  Add an ability to share a link to a single sChain in proxy UI (display only this chain)
- [x] Add copy button to copy all info about the chain to the clipboard (HTTP/WS/FS/chain id, block explorer, etc)
- [x] `Connect to sChain` button to load info such as current block, etc

**Comment by gannakulikova** [comment]
Done
